set -g @plugin 'rose-pine/tmux'
set -g @plugin 'tmux-plugins/tpm'
set -g @rose_pine_variant 'moon' # Options are 'main', 'moon' or 'dawn'
set -g @rose_pine_host 'on' # Enables hostname in the status bar
set -g @rose_pine_date_time '%I:%M on %A %D' # It accepts the date UNIX command format (man date for info)
set -g @rose_pine_user 'on' # Turn on the username component in the statusbar
set -g @rose_pine_directory 'off' # Turn on the current folder component in the status bar
set -g @rose_pine_bar_bg_disable 'off' # Disables background color, for transparent terminal emulators

set -g @rose_pine_left_separator '  '
set -g @rose_pine_window_separator '  '


set -s escape-time 0
set -g clock-mode-style 12
set -g default-terminal "tmux-256color"

unbind C-b
set -g prefix 'C-\'

run '~/.tmux/plugins/tpm/tpm'
