#!/bin/bash
#
# Linux, install stuff
installOSPackages() {
    . /etc/os-release; DISTRO=$ID_LIKE
    if [[ $DISTRO == "debian" || $DISTRO == "ubuntu" ]]; then
        sudo apt install python3 -y
        sudo apt install texlive-full
        python3 -m ensurepip --upgrade
        python3 -m pip install --user --upgrade pynvim
        # sudo apt install neovim
    elif [[ $DISTRO == "fedora" ]]; then
        sudo yum install python3
        sudo yum install texlive-scheme-full
        python3 -m ensurepip --upgrade
        python3 -m pip install --user --upgrade pynvim
        # sudo yum install neovim
    else
        echo "Can't find package manager. You must install:"
        echo "python3"
    fi
}

installNeovim() {
    curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
    sudo rm -rf /opt/nvim
    sudo tar -C /opt -xzf nvim-linux64.tar.gz
    rm nvim-linux64.tar.gz
    touch $HOME/.bashrc
    touch $HOME/.zshrc
    echo 'export PATH="$PATH:/opt/nvim-linux64/bin"' >> $HOME/.bashrc
    echo 'export PATH="$PATH:/opt/nvim-linux64/bin"' >> $HOME/.zshrc
    echo 'Installed neovim!'
}

if [[ "$OSTYPE" == "darwin"* || "$OSTYPE" == "linux"* ]]; then
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
    nvm install --latest-npm
    echo 'Installed nvm and npm!'
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
else
    echo "Are you on Windows? I do not and will not include a bootstrap for Windows. Sorry!"
    exit 1;
fi

# MacOS, install stuff
if [[ "$OSTYPE" == "darwin"* ]]; then
    if [$? != 0]; then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        brew install neovim
        brew install mactex-no-gui
        echo 'Installed brew!'
    fi
else
    installOSPackages
fi

installNeovim
